---
driver:
  name: docker

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true
  username: tomcat
  password: tomcat

platforms:
  - name: windows-2012R2
    driver:
      customize:
        memory: 4096

suites:
  - name: default
    run_list:
      - recipe[apache::blank]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
